import { useEffect } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { useAuth } from "../auth/AuthProvider";
import { approve, getIncident, reject } from "../features/incidents/api";
import { AuditPanel } from "../features/incidents/AuditPanel";
import { EvidencePanel } from "../features/incidents/EvidencePanel";
import { IncidentOverview } from "../features/incidents/IncidentOverview";
import { IncidentTimeline } from "../features/incidents/IncidentTimeline";
import { KnowledgePanel } from "../features/incidents/KnowledgePanel";
import { RemediationPanel } from "../features/incidents/RemediationPanel";

export function IncidentDetailPage() { const { incidentId = "" } = useParams(); const { client, user } = useAuth(); const cache = useQueryClient(); const query = useQuery({ queryKey: ["incident", incidentId], queryFn: () => getIncident(client, incidentId), enabled: Boolean(incidentId) }); const refresh = () => cache.invalidateQueries({ queryKey: ["incident", incidentId] }); const approval = useMutation({ mutationFn: (hash: string) => approve(client, incidentId, hash), onSuccess: refresh }); const rejection = useMutation({ mutationFn: (hash: string) => reject(client, incidentId, hash), onSuccess: refresh }); useEffect(() => { let cancelled = false; let reader: ReadableStreamDefaultReader<Uint8Array> | undefined; const start = async () => { try { const response = await client.openStream(`/api/v1/incidents/${incidentId}/stream`); reader = response.body!.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (!cancelled) { const item = await reader.read(); if (item.done) break; buffer += decoder.decode(item.value, { stream: true }); while (buffer.includes("\n\n")) { buffer = buffer.slice(buffer.indexOf("\n\n") + 2); refresh(); } } } catch { /* reconnect is naturally handled on next navigation/refresh */ } }; if (incidentId) void start(); return () => { cancelled = true; void reader?.cancel(); }; }, [client, incidentId, refresh]); if (query.isLoading) return <p>正在加载…</p>; if (query.error || !query.data) return <p className="error">{query.error?.message ?? "Incident 不存在"}</p>; const detail = query.data; const canApprove = user?.role === "approver" || user?.role === "admin"; return <main><p><Link to="/incidents">← 返回列表</Link></p><IncidentOverview overview={detail.overview} /><IncidentTimeline events={detail.audit_events} /><EvidencePanel evidence={detail.evidence} hypotheses={detail.hypotheses} /><KnowledgePanel citations={detail.knowledge_citations} /><RemediationPanel plans={detail.action_plans} canApprove={canApprove} onApprove={(hash) => approval.mutate(hash)} onReject={(hash) => rejection.mutate(hash)} />{(approval.error || rejection.error) && <p className="error">{String(approval.error ?? rejection.error)}</p>}<AuditPanel events={detail.audit_events} /></main>; }
